# Configuration for a Dark Forest universe
# Defined in TOML as per https://toml.io/en/v0.5.0

[initializers]
ADMIN_CAN_ADD_PLANETS = true
WORLD_RADIUS_LOCKED = false # if true will keep universe radius at INITIAL_WORLD_RADIUS
TOKEN_MINT_END_TIMESTAMP = 2022-01-04T15:35:00.000Z  # Jan 4, 2022, 11:59:00 PM (EST)
TARGET4_RADIUS = 8000 # 
INITIAL_WORLD_RADIUS = 8000 # Cray!

##################################
# SNARK keys & Perlin parameters #
##################################
DISABLE_ZK_CHECKS = true
PLANETHASH_KEY = 6278
SPACETYPE_KEY = 6279
BIOMEBASE_KEY = 6270
PERLIN_MIRROR_X = false
PERLIN_MIRROR_Y = false
PERLIN_LENGTH_SCALE = 16384 # must be a power of two no greater than 16384

######################
# Game configuration #
######################
# NOTE that START TIME and END TIME will be set in `settings.ts` as the default.
MIN_RADIUS = 2000
SHRINK_FACTOR = 2
SHRINK = true
# SHRINK_START = 2021-12-27T00:00:00.000Z Dec 26, 2021, 4:00:00 PM EST 
# ROUND_END = 2021-12-27T02:00:00.000Z Dec 26, 2021, 6:00:00 PM 
DISC_LOWER_BOUND = 50 # determines spawn min for shrinking universe
DISC_UPPER_BOUND = 75 # determines spawn max for shrinking universe
DESTROY_THRESHOLD = 2 # must be an integer, default is 0.   
MAX_NATURAL_PLANET_LEVEL = 256
TIME_FACTOR_HUNDREDTHS = 6000 # speedup/slowdown game
PERLIN_THRESHOLD_1 = 14
PERLIN_THRESHOLD_2 = 15
PERLIN_THRESHOLD_3 = 19
INIT_PERLIN_MIN = 1 # determines where players can spawn
INIT_PERLIN_MAX = 25 # determines where players can spawn
SPAWN_RIM_AREA = 0
BIOME_THRESHOLD_1 = 15
BIOME_THRESHOLD_2 = 17
PLANET_RARITY = 32768 # 16384 determines frequency of each planet
PHOTOID_ACTIVATION_DELAY = 14400 # seconds
LOCATION_REVEAL_COOLDOWN = 86400 # seconds
CLAIM_PLANET_COOLDOWN = 10800 # seconds
PLANET_TYPE_WEIGHTS = [
  [
    [1, 0, 0, 0, 0],
    [13, 2, 0, 1, 0],
    [13, 2, 0, 1, 0],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
    [13, 2, 0, 0, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [13, 2, 1, 0, 0],
    [12, 2, 1, 1, 0],
    [11, 2, 1, 1, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
    [12, 2, 1, 0, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [10, 4, 2, 0, 0],
    [10, 4, 1, 1, 0],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
    [8, 4, 1, 2, 1],
  ],
  [
    [1, 0, 0, 0, 0],
    [11, 4, 1, 0, 0],
    [11, 4, 1, 0, 0],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
    [7, 4, 2, 2, 1],
  ],
]


##########################
# Planets to add to game #
##########################
